language: ruby
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.10'
  - '2.3.8'
  - '2.4.5'
  - '2.5.3'
  - '2.6.0'
  - 'jruby-head'
script:
  - bundle exec appraisal rspec
before_install:
  - gem update bundler
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database myapp_test;' -U postgres
  - cp .travis.database.yml spec/db/database.yml
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec appraisal install --jobs=3 --retry=3
matrix:
  include:
    - env: RUBOCOP=✓
      rvm: '2.5.3'
      script: bundle exec rubocop
      before_install:
    - env: CHECK_RUBIES=✓
      rvm: '2.5.3'
      script: bundle exec travis_check_rubies
      before_install:
  allow_failures:
    - rvm: 'jruby-head'
