sudo: false
dist: trusty
language: ruby
addons:
  postgresql: '9.3'
rvm:
  - '1.9.3-p551'
  - '2.2.10'
  - '2.3.8'
  - '2.4.10'
  - '2.5.8'
  - '2.6.6'
  - '2.7.2'
  - 'jruby-head'
script:
  - ./bundle exec appraisal rspec
before_install:
  - gem install bundler --version '< 2'
  - ruby -rrubygems -e 'puts "#!/bin/sh", %{bundle _#{Gem::Dependency.new("bundler", "< 2.0").to_spec.version}_ "$@"}' > bundle
  - chmod +x bundle
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database myapp_test;' -U postgres
  - cp .travis.database.yml spec/db/database.yml
  - psql --version
  - psql -c 'SELECT version();' -U postgres
install:
  - ./bundle install --jobs=3 --retry=3
  - ./bundle exec appraisal install --jobs=3 --retry=3
matrix:
  include:
    - env: RUBOCOP=1
      rvm: '2.6.6'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=1
      rvm: '2.6.6'
      script: bundle exec travis_check_rubies
  allow_failures:
    - rvm: 'jruby-head'
