language: ruby
script: bundle exec rspec
before_install:
  - gem update bundler
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database myapp_test;' -U postgres
  - cp .travis.database.yml spec/db/database.yml
matrix:
  include:
    - env: RAILS_VERSION='~> 2.3'
      rvm: '1.8.7-p371'
    - env: RAILS_VERSION='~> 2.3'
      rvm: '1.9.3-p551'
    - env: RAILS_VERSION='~> 3.2'
      rvm: '1.9.3-p551'
    - env: RAILS_VERSION='~> 4.0'
      rvm: '2.0.0-p648'
    - env: RAILS_VERSION='~> 5.0'
      rvm: '2.2.9'
    - env: RAILS_VERSION='~> 5.0'
      rvm: '2.3.6'
    - env: RAILS_VERSION='~> 5.0'
      rvm: '2.4.3'
    - env: RUBOCOP=✓
      rvm: '2.4.3'
      script: bundle exec rubocop
      before_install:
    - env: CHECK_RUBIES=✓
      rvm: '2.4.3'
      script: bundle exec travis_check_rubies
      before_install:
