# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dump}
  s.version = "0.0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ivan Kuchin"]
  s.date = %q{2010-12-23}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".tmignore",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "assets.example",
    "gems/archive-tar-minitar-0.5.2/ChangeLog",
    "gems/archive-tar-minitar-0.5.2/Install",
    "gems/archive-tar-minitar-0.5.2/README",
    "gems/archive-tar-minitar-0.5.2/Rakefile",
    "gems/archive-tar-minitar-0.5.2/bin/minitar",
    "gems/archive-tar-minitar-0.5.2/lib/archive/tar/minitar.rb",
    "gems/archive-tar-minitar-0.5.2/lib/archive/tar/minitar/command.rb",
    "gems/archive-tar-minitar-0.5.2/tests/tc_tar.rb",
    "gems/archive-tar-minitar-0.5.2/tests/testall.rb",
    "gems/progress-1.0.1/.gitignore",
    "gems/progress-1.0.1/Manifest",
    "gems/progress-1.0.1/README.rdoc",
    "gems/progress-1.0.1/Rakefile",
    "gems/progress-1.0.1/VERSION",
    "gems/progress-1.0.1/lib/progress.rb",
    "gems/progress-1.0.1/lib/progress/active_record.rb",
    "gems/progress-1.0.1/lib/progress/enumerable.rb",
    "gems/progress-1.0.1/lib/progress/integer.rb",
    "gems/progress-1.0.1/lib/progress/kernel.rb",
    "gems/progress-1.0.1/lib/progress/with_progress.rb",
    "gems/progress-1.0.1/progress.gemspec",
    "gems/progress-1.0.1/spec/progress_spec.rb",
    "gems/progress-1.0.1/spec/spec_helper.rb",
    "install.rb",
    "lib/backported_tmpdir.rb",
    "lib/continious_timeout.rb",
    "lib/dump.rb",
    "lib/dump/railtie.rb",
    "lib/dump_rake.rb",
    "lib/dump_rake/assets.rb",
    "lib/dump_rake/dump.rb",
    "lib/dump_rake/dump_reader.rb",
    "lib/dump_rake/dump_writer.rb",
    "lib/dump_rake/env.rb",
    "lib/dump_rake/env/filter.rb",
    "lib/dump_rake/rails_root.rb",
    "lib/dump_rake/table_manipulation.rb",
    "lib/shell_escape.rb",
    "lib/tasks/assets.rake",
    "lib/tasks/dump.rake",
    "recipes/dump.rb",
    "spec/cycle_spec.rb",
    "spec/db/database.example.yml",
    "spec/db/schema.rb",
    "spec/lib/dump_rake/dump_reader_spec.rb",
    "spec/lib/dump_rake/dump_spec.rb",
    "spec/lib/dump_rake/dump_writer_spec.rb",
    "spec/lib/dump_rake/env/filter_spec.rb",
    "spec/lib/dump_rake/env_spec.rb",
    "spec/lib/dump_rake/rails_root_spec.rb",
    "spec/lib/dump_rake/table_manipulation_spec.rb",
    "spec/lib/dump_rake_spec.rb",
    "spec/recipes/dump_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/tasks/assets_spec.rb",
    "spec/tasks/dump_spec.rb"
  ]
  s.homepage = %q{http://github.com/toy/dump}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails app rake and capistrano tasks to create and restore dumps of database and assets}
  s.test_files = [
    "spec/cycle_spec.rb",
    "spec/db/schema.rb",
    "spec/lib/dump_rake/dump_reader_spec.rb",
    "spec/lib/dump_rake/dump_spec.rb",
    "spec/lib/dump_rake/dump_writer_spec.rb",
    "spec/lib/dump_rake/env/filter_spec.rb",
    "spec/lib/dump_rake/env_spec.rb",
    "spec/lib/dump_rake/rails_root_spec.rb",
    "spec/lib/dump_rake/table_manipulation_spec.rb",
    "spec/lib/dump_rake_spec.rb",
    "spec/recipes/dump_spec.rb",
    "spec/spec_helper.rb",
    "spec/tasks/assets_spec.rb",
    "spec/tasks/dump_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rake-gem-ghost>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rake-gem-ghost>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rake-gem-ghost>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

