source 'http://rubygems.org'

gem 'rails', '3.1.3'

gem 'sqlite3'
gem 'json'
gem 'jquery-rails'

group :assets do
  gem 'sass-rails', '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.6'
end

gem 'dump', :path => '../../..'
