#!/usr/bin/env ruby -rrubygems

$: << File.join(File.dirname(__FILE__), '../lib')
require 'pathname'
require 'dump_rake/env'

readme = Pathname('README.markdown')
lines = readme.readlines.map(&:rstrip)
readme.open('w') do |f|
  lines.each do |line|
    line.sub!(/^`(.+?)`.*—.*$/) do
      key, names = DumpRake::Env::DICTIONARY.find{ |key, values| values.include?($1)  }
      if key
        names = names.map{ |name| "`#{name}`" }.join(', ')
        explanation = DumpRake::Env::EXPLANATIONS[key]
        "#{names} — #{explanation}"
      end
    end
    f.puts line
  end
end
