name: check
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 4
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - '1.9'
        - '2.0'
        - '2.1'
        - '2.2'
        - '2.3'
        - '2.4'
        - '2.5'
        - '2.6'
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
        - jruby-9.3
        - jruby-9.4
      fail-fast: false
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
          MYSQL_DATABASE: dump_test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
        ports:
          - 3306:3306
      postgres:
        image: postgres:9.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dump_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - if: ${{ matrix.container >= 'ruby:1.9' && matrix.container < 'ruby:2.3' }}
      run: |
        echo "gem: --no-ri --no-rdoc --no-document" > ~/.gemrc
        gem install rubygems-update --version '< 3'
        update_rubygems
        gem install bundler --version '< 2'
    - run: |
        tee spec/db/database.yml << YAML
        sqlite3:
          adapter: sqlite3
          database: ':memory:'

        mysql:
          adapter: mysql2
          host: 127.0.0.1
          database: dump_test
          username: mysql
          password: mysql
          encoding: utf8

        postgresql:
          adapter: postgresql
          host: localhost
          database: dump_test
          username: postgres
          password: postgres
        YAML
    - run: bundle install --jobs=3 --retry=3
    - run: RUBYOPT=-rset bundle exec appraisal install --jobs=3 --retry=3
    - run: bundle exec appraisal rspec
