name: rubocop
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 4
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - run: bundle exec rubocop
